apiVersion: v1
kind: Service
metadata:
  name: bedrock-gateway-svc
  namespace: openwebui
  labels:
    app: bedrock-gateway-svc
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: bedrock-gateway
  type: ClusterIP