apiVersion: v1
kind: Service
metadata:
  name: ollama-svc
  namespace: openwebui
  labels:
    app: ollama-svc
spec:
  ports:
  - port: 80
    targetPort: 11434
    protocol: TCP
  selector:
    app: ollama
  type: ClusterIP