apiVersion: v1
kind: Service
metadata:
  name: pipelines-svc
  namespace: openwebui
  labels:
    app: pipelines-svc
spec:
  ports:
  - port: 80
    targetPort: 9099
    protocol: TCP
  selector:
    app: pipelines
  type: ClusterIP