apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: openwebui
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0%
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: IMAGE
        env:
        - name: WEBUI_SECRET_KEY
          value: ""
        - name: ENABLE_SIGNUP
          value: "true"
        - name: DATABASE_URL
          valueFrom: 
            secretKeyRef: 
              key: DATABASE_URL
              name: open-webui-secret
        - name: OLLAMA_BASE_URL
          value: "http://ollama-svc.openwebui.svc.cluster.local:80"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 50
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 60
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 50
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 60
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "/mnt/prestop.sh"]
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
          limits:
            cpu: 2000m
            memory: 2000Mi
        ports:
          - containerPort: 8080
        tty: true
        volumeMounts:
        - name: webui-volume
          mountPath: /app/backend/data
      volumes:
      - name: webui-volume
        persistentVolumeClaim:
          claimName: open-webui-pvc